### ISSUE TITLE
I died twice and counts for incorrect position

### ISSUE THREAD

**Issue by WSDguy2014** [TalkLounge/death_pos#1]
I tested on multiplayer for example Sky Wars, i died twice. First, i died on permanent fire then i click respawn for correct timing and i died again second one on spawn, because player detection is bad and it detects per second, not instantly like in Minecraft. I checked what i died, it checks that i died on spawn point, not on permanent fire for first time.

**Comment by TalkLounge** [comment]
Sorry, but that's a bug from minetest itself, that the death function triggers to late. What could help is to wait a second before respawn.
